// position.idl
struct Position {
    string timestamp;
    string route;
    string vehicle;
    long stopNumber;
    long numStops;
    double timeBetweenStops;
    string trafficConditions;
    long fillInRatio;
}; //@top-level

// accident.idl
struct Accident {
    string timestamp;
    string route;
    string vehicle;
    long stopNumber;
}; //@top-level
